//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.PiperChatClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/PiperchatService.Models")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfApp1.PiperChatClient.Message[] UserMessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfApp1.PiperChatClient.Message[] UserMessages {
            get {
                return this.UserMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.UserMessagesField, value) != true)) {
                    this.UserMessagesField = value;
                    this.RaisePropertyChanged("UserMessages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/PiperchatService.Models")]
    [System.SerializableAttribute()]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageSentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReceiverIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SenderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeSentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageSent {
            get {
                return this.MessageSentField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageSentField, value) != true)) {
                    this.MessageSentField = value;
                    this.RaisePropertyChanged("MessageSent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReceiverId {
            get {
                return this.ReceiverIdField;
            }
            set {
                if ((this.ReceiverIdField.Equals(value) != true)) {
                    this.ReceiverIdField = value;
                    this.RaisePropertyChanged("ReceiverId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SenderId {
            get {
                return this.SenderIdField;
            }
            set {
                if ((this.SenderIdField.Equals(value) != true)) {
                    this.SenderIdField = value;
                    this.RaisePropertyChanged("SenderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeSent {
            get {
                return this.TimeSentField;
            }
            set {
                if ((this.TimeSentField.Equals(value) != true)) {
                    this.TimeSentField = value;
                    this.RaisePropertyChanged("TimeSent");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PiperChatClient.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/InsertUserRecord", ReplyAction="http://tempuri.org/IUserService/InsertUserRecordResponse")]
        string InsertUserRecord(WpfApp1.PiperChatClient.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/InsertUserRecord", ReplyAction="http://tempuri.org/IUserService/InsertUserRecordResponse")]
        System.Threading.Tasks.Task<string> InsertUserRecordAsync(WpfApp1.PiperChatClient.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateUserRecord", ReplyAction="http://tempuri.org/IUserService/UpdateUserRecordResponse")]
        string UpdateUserRecord(WpfApp1.PiperChatClient.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateUserRecord", ReplyAction="http://tempuri.org/IUserService/UpdateUserRecordResponse")]
        System.Threading.Tasks.Task<string> UpdateUserRecordAsync(WpfApp1.PiperChatClient.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeleteUserRecord", ReplyAction="http://tempuri.org/IUserService/DeleteUserRecordResponse")]
        string DeleteUserRecord(WpfApp1.PiperChatClient.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeleteUserRecord", ReplyAction="http://tempuri.org/IUserService/DeleteUserRecordResponse")]
        System.Threading.Tasks.Task<string> DeleteUserRecordAsync(WpfApp1.PiperChatClient.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/SearchUserRecord", ReplyAction="http://tempuri.org/IUserService/SearchUserRecordResponse")]
        System.Data.DataSet SearchUserRecord(WpfApp1.PiperChatClient.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/SearchUserRecord", ReplyAction="http://tempuri.org/IUserService/SearchUserRecordResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SearchUserRecordAsync(WpfApp1.PiperChatClient.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAllUserRecords", ReplyAction="http://tempuri.org/IUserService/GetAllUserRecordsResponse")]
        System.Data.DataSet GetAllUserRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAllUserRecords", ReplyAction="http://tempuri.org/IUserService/GetAllUserRecordsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllUserRecordsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Validate", ReplyAction="http://tempuri.org/IUserService/ValidateResponse")]
        string Validate(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Validate", ReplyAction="http://tempuri.org/IUserService/ValidateResponse")]
        System.Threading.Tasks.Task<string> ValidateAsync(string email, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : WpfApp1.PiperChatClient.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<WpfApp1.PiperChatClient.IUserService>, WpfApp1.PiperChatClient.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string InsertUserRecord(WpfApp1.PiperChatClient.User user) {
            return base.Channel.InsertUserRecord(user);
        }
        
        public System.Threading.Tasks.Task<string> InsertUserRecordAsync(WpfApp1.PiperChatClient.User user) {
            return base.Channel.InsertUserRecordAsync(user);
        }
        
        public string UpdateUserRecord(WpfApp1.PiperChatClient.User user) {
            return base.Channel.UpdateUserRecord(user);
        }
        
        public System.Threading.Tasks.Task<string> UpdateUserRecordAsync(WpfApp1.PiperChatClient.User user) {
            return base.Channel.UpdateUserRecordAsync(user);
        }
        
        public string DeleteUserRecord(WpfApp1.PiperChatClient.User user) {
            return base.Channel.DeleteUserRecord(user);
        }
        
        public System.Threading.Tasks.Task<string> DeleteUserRecordAsync(WpfApp1.PiperChatClient.User user) {
            return base.Channel.DeleteUserRecordAsync(user);
        }
        
        public System.Data.DataSet SearchUserRecord(WpfApp1.PiperChatClient.User user) {
            return base.Channel.SearchUserRecord(user);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SearchUserRecordAsync(WpfApp1.PiperChatClient.User user) {
            return base.Channel.SearchUserRecordAsync(user);
        }
        
        public System.Data.DataSet GetAllUserRecords() {
            return base.Channel.GetAllUserRecords();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllUserRecordsAsync() {
            return base.Channel.GetAllUserRecordsAsync();
        }
        
        public string Validate(string email, string password) {
            return base.Channel.Validate(email, password);
        }
        
        public System.Threading.Tasks.Task<string> ValidateAsync(string email, string password) {
            return base.Channel.ValidateAsync(email, password);
        }
    }
}
